config/routes.rb
Rails.application.routes.draw do
  resources :no_dues
  resources :subjects
  resources :academic_sessions
  get 'welcome/index'
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'welcome#index'
end

app/models/no_due.rb
class NoDue < ApplicationRecord
  belongs_to :user
  belongs_to :academic_session
end

app/controllers/no_dues_controller.rb
class NoDuesController < ApplicationController
  before_action :set_no_due, only: [:show, :edit, :update, :destroy]

  # GET /no_dues
  # GET /no_dues.json
  def index
    @no_dues = NoDue.all
  end

  # GET /no_dues/1
  # GET /no_dues/1.json
  def show
  end

  # GET /no_dues/new
  def new
    @no_due = NoDue.new
  end

  # GET /no_dues/1/edit
  def edit
  end

  # POST /no_dues
  # POST /no_dues.json
  def create
    @no_due = NoDue.new(no_due_params)

    respond_to do |format|
      if @no_due.save
        format.html { redirect_to @no_due, notice: 'No due was successfully created.' }
        format.json { render :show, status: :created, location: @no_due }
      else
        format.html { render :new }
        format.json { render json: @no_due.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /no_dues/1
  # PATCH/PUT /no_dues/1.json
  def update
    respond_to do |format|
      if @no_due.update(no_due_params)
        format.html { redirect_to @no_due, notice: 'No due was successfully updated.' }
        format.json { render :show, status: :ok, location: @no_due }
      else
        format.html { render :edit }
        format.json { render json: @no_due.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /no_dues/1
  # DELETE /no_dues/1.json
  def destroy
    @no_due.destroy
    respond_to do |format|
      format.html { redirect_to no_dues_url, notice: 'No due was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_no_due
      @no_due = NoDue.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def no_due_params
      params.require(:no_due).permit(:user_id, :academic_session_id, subject_ids: [])
    end
end

app/helpers/no_dues_helper.rb
module NoDuesHelper
end

app/views/no_dues/_form.html.erb
<%= form_with(model: no_due, local: true) do |form| %>
  <% if no_due.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(no_due.errors.count, "error") %> prohibited this no_due from being saved:</h2>

      <ul>
      <% no_due.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :user_id %>
    <%= form.text_field :user_id, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :academic_session_id %>
    <%= form.text_field :academic_session_id, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :subject %>
    <br>
    <% Subject.pluck(:name).each do |subject| %>
      <%= form.check_box :subject_ids, { multiple: true }, subject, false %>
      <%= subject %>
      <br>
    <% end %>
  </div>

  <div class="actions">
    <%= form.submit "Create NO_DUES", class: "btn btn-primary" %>
    <%= link_to "Back", :back, class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/no_dues/edit.html.erb
<h1>Editing No Due</h1>

<%= render 'form', no_due: @no_due %>

<%= link_to 'Show', @no_due %> |
<%= link_to 'Back', no_dues_path %>

app/views/no_dues/index.html.erb
<div class="container">
  <p id="notice"><%= notice %></p>

  <h1>No Dues</h1>

  <table class="table">
    <thead>
      <tr>
        <th>User</th>
        <th>Academic session</th>
        <th>Subject ids</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @no_dues.each do |no_due| %>
        <tr>
          <td><%= no_due.user.username %></td>
          <td><%= no_due.academic_session.title %></td>
          <td><%= no_due.subject_ids.join(',') %></td>
          <td><%= link_to 'Show', no_due %></td>
          <td><%= link_to 'Edit', edit_no_due_path(no_due) %></td>
          <td><%= link_to 'Destroy', no_due, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>

  <%= link_to 'New No Due', new_no_due_path, class: "btn btn-primary" %>

</div>

app/views/no_dues/new.html.erb
<div class="container">
  <h1>New No Dues Form</h1>
  <%= render 'form', no_due: @no_due %>
</div>

app/views/no_dues/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @no_due.user.username %>
</p>

<p>
  <strong>Academic session:</strong>
  <%= @no_due.academic_session.title %>
</p>

<p>
  <strong>Subject ids:</strong>
  <%= @no_due.subject_ids %>
</p>

<%= link_to 'Edit', edit_no_due_path(@no_due) %> |
<%= link_to 'Back', no_dues_path %>