config/routes.rb
Rails.application.routes.draw do
  resources :no_dues
  resources :subjects
  resources :academic_sessions
  get 'welcome/index'
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'welcome#index'
end

app/models/academic_session.rb
class AcademicSession < ApplicationRecord
  has_and_belongs_to_many :users
end

app/controllers/academic_sessions_controller.rb
class AcademicSessionsController < ApplicationController
  before_action :set_academic_session, only: [:show, :edit, :update, :destroy]

  # GET /academic_sessions
  # GET /academic_sessions.json
  def index
    @academic_sessions = AcademicSession.all
  end

  # GET /academic_sessions/1
  # GET /academic_sessions/1.json
  def show
  end

  # GET /academic_sessions/new
  def new
    @academic_session = AcademicSession.new
  end

  # GET /academic_sessions/1/edit
  def edit
  end

  # POST /academic_sessions
  # POST /academic_sessions.json
  def create
    @academic_session = AcademicSession.new(academic_session_params)

    respond_to do |format|
      if @academic_session.save
        format.html { redirect_to @academic_session, notice: 'Academic session was successfully created.' }
        format.json { render :show, status: :created, location: @academic_session }
      else
        format.html { render :new }
        format.json { render json: @academic_session.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /academic_sessions/1
  # PATCH/PUT /academic_sessions/1.json
  def update
    respond_to do |format|
      if @academic_session.update(academic_session_params)
        format.html { redirect_to @academic_session, notice: 'Academic session was successfully updated.' }
        format.json { render :show, status: :ok, location: @academic_session }
      else
        format.html { render :edit }
        format.json { render json: @academic_session.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /academic_sessions/1
  # DELETE /academic_sessions/1.json
  def destroy
    @academic_session.destroy
    respond_to do |format|
      format.html { redirect_to academic_sessions_url, notice: 'Academic session was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_academic_session
      @academic_session = AcademicSession.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def academic_session_params
      params.require(:academic_session).permit(:title, :from, :to)
    end
end

app/helpers/academic_sessions_helper.rb
module AcademicSessionsHelper
end

app/views/academic_sessions/_form.html.erb
<%= form_with(model: academic_session, local: true) do |form| %>
  <% if academic_session.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(academic_session.errors.count, "error") %> prohibited this academic_session from being saved:</h2>

      <ul>
      <% academic_session.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :title %>
    <%= form.text_field :title, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :from %>
    <%= form.date_select :from , class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :to %>
    <%= form.date_select :to, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.submit :class => 'btn btn-primary' %>
  </div>
<% end %>

app/views/academic_sessions/edit.html.erb
<h1>Editing Academic Session</h1>

<%= render 'form', academic_session: @academic_session %>

<%= link_to 'Show', @academic_session %> |
<%= link_to 'Back', academic_sessions_path %>

app/views/academic_sessions/index.html.erb
<div class="container">
  <p id="notice"><%= notice %></p>
  <h1>Academic Sessions</h1>
  <table class="table">
    <thead>
      <tr>
        <th>Title</th>
        <th>From</th>
        <th>To</th>
        <th colspan="3"></th>
      </tr>
    </thead>
    <tbody>
      <% @academic_sessions.each do |academic_session| %>
        <tr>
          <td><%= academic_session.title %></td>
          <td><%= academic_session.from %></td>
          <td><%= academic_session.to %></td>
          <td><%= link_to 'Show', academic_session %></td>
          <td><%= link_to 'Edit', edit_academic_session_path(academic_session) %></td>
          <td><%= link_to 'Destroy', academic_session, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <br>
  <%= link_to 'New Academic Session', new_academic_session_path, class: 'btn btn-primary' %>
</div>

app/views/academic_sessions/new.html.erb
<div class="container">
  <h1>New Academic Session</h1>
  <%= render 'form', academic_session: @academic_session %>
  <%= link_to 'Back', academic_sessions_path %>
</div>

app/views/academic_sessions/show.html.erb
<div class="container">
  <p id="notice"><%= notice %></p>

  <p>
    <strong>Title:</strong>
    <%= @academic_session.title %>
  </p>

  <p>
    <strong>From:</strong>
    <%= @academic_session.from %>
  </p>

  <p>
    <strong>To:</strong>
    <%= @academic_session.to %>
  </p>

  <%= link_to 'Edit', edit_academic_session_path(@academic_session) %> |
  <%= link_to 'Back', academic_sessions_path %>

</div>